import "./globals.css";
import Header from "./components/Header";
import { GoogleFonts } from "next-google-fonts";


function MyApp({ Component, pageProps }) {
  return (
    <>
      <GoogleFonts href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&family=Libre+Baskerville:wght@400;700&display=swap" />
      <Component {...pageProps} />
    </>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-brand-beige-10" lang="en">
      <body style={{ fontFamily: "Poppins, sans-serif" }}>
        <Header />
        {children}
      </body>
    </html>
  );
}