import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-farve-1" lang="en">
      <body style={{ fontFamily: "Poppins, sans-serif" }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
